// date must be in format yyyy-mm-dd

const DRUMS = "Bicí";
const LEAD_GUITAR = "Melodická kytara";
const RHYTHM_GUITAR = "Rytmická kytara";
const SINGER = "Hlavní zpěv";
const BACKING_VOCALS = "Doprovodný zpěv";
const BASS = "Baskytara";
const today = () =>
  `${new Date().getFullYear()}-${
    new Date().getMonth() + 1
  }-${new Date().getDate()}`;

babylon = {
  photographers: [
    {
      id: "MV",
      name: "Marie Veselá",
      web: "https://www.mayvesela.cz/",
    },
    {
      id: "KG",
      name: "Klára Galle",
      web: "https://klaragalle.com/",
    },
    {
      id: "MD",
      name: "Mery Dvořáková",
    },
    {
      id: "LZ",
      name: "Lukáš Zima",
      web: "https://www.lukaszima-fotovideo.cz/",
    },
    {
      id: "KK",
      name: "Kamila Kubásková",
      web: "https://linktr.ee/kubaskovafoto",
    },
  ],
  members: [
    {
      name: "Matouš",
      positions: [
        {
          title: SINGER,
          since: "2013-1-1",
          to: "2016-12-31",
        },
        {
          title: LEAD_GUITAR,
          since: "2013-1-1",
          to: "2016-12-31",
        },
      ],
    },
    {
      name: "Jirka",
      positions: [
        {
          title: DRUMS,
          since: "2013-1-1",
          to: "2016-12-31",
        },
        {
          title: BACKING_VOCALS,
          since: "2013-1-1",
          to: "2016-12-31",
        },
        {
          title: SINGER,
          since: "2017-1-1",
          to: today(),
        },
      ],
    },
    {
      name: "David",
      positions: [
        {
          title: RHYTHM_GUITAR,
          since: "2013-1-1",
          to: today(),
        },
        {
          title: BACKING_VOCALS,
          since: "2013-1-1",
          to: today(),
        },
      ],
    },
    {
      name: "Pavel",
      positions: [
        {
          title: BASS,
          since: "2013-1-1",
          to: "2022-12-31",
        },
        {
          title: LEAD_GUITAR,
          since: "2023-9-1",
          to: today(),
        },
      ],
    },
    {
      name: "Miky",
      positions: [
        {
          title: DRUMS,
          since: "2017-9-1",
          to: "2018-9-1",
        },
      ],
    },
    {
      name: "Timmy",
      positions: [
        {
          title: LEAD_GUITAR,
          since: "2017-6-1",
          to: "2023-8-31",
        },
        {
          title: BACKING_VOCALS,
          since: "2022-1-1",
          to: "2023-8-31",
        },
      ],
    },
    {
      name: "Patrik",
      positions: [
        {
          title: DRUMS,
          since: "2019-3-1",
          to: "2022-3-31",
        },
      ],
    },
    {
      name: "Honza",
      positions: [
        {
          title: DRUMS,
          since: "2022-4-1",
          to: today(),
        },
      ],
    },
    {
      name: "Radim",
      positions: [
        {
          title: BASS,
          since: "2023-1-1",
          to: today(),
        },
      ],
    },
  ],
  gigs: [
    {
      title: "Millenium club",
      place: "Bystřice nad Pernštejnem",
      date: "2013-4-13",
      acoustic: false,
    },
    {
      title: "Millenium club",
      place: "Bystřice nad Pernštejnem",
      date: "2013-4-26",
      acoustic: false,
    },
    {
      title: "Majíles Zubří země",
      place: "Bystřice nad Pernštejnem",
      date: "2013-5-10",
      acoustic: false,
    },
    {
      title: "Slavnostní vyřazení maturantů",
      place: "Bystřice nad Pernštejnem, gymnázium",
      date: "2013-5-30",
      acoustic: true,
    },
    {
      title: "Zastávka Dalečín",
      place: "Dalečín",
      date: "2013-6-21",
      acoustic: false,
    },
    {
      title: "Rodinná oslava (Vrbíkovi)",
      place: "Bystřice nad Pernštejnem",
      date: "2013-6-21",
      acoustic: false,
    },
    {
      title: "Pelíšek fest",
      place: "Bystřice nad Pernštejnem",
      date: "2013-6-29",
      acoustic: false,
    },
    {
      title: "Backstage of Stařec",
      place: "Stařeč",
      date: "2013-7-20",
      acoustic: false,
    },
    {
      title: "Sulíkov",
      place: "Sulíkov",
      date: "2013-8-30",
      acoustic: false,
    },
    {
      title: "Funny Fest (Nadosah)",
      place: "Bystřice nad Pernštejnem",
      date: "2013-9-27",
      acoustic: false,
    },
    {
      title: "Millenium club",
      place: "Bystřice nad Pernštejnem",
      date: "2013-9-28",
      acoustic: false,
    },
    {
      title: "Dačice",
      place: "Dačice, klub Kostka",
      date: "2013-10-19",
      acoustic: false,
    },
    {
      title: "ProRock",
      place: "Praha",
      date: "2013-11-9",
      acoustic: false,
    },
    {
      title: "Crush the school",
      place: "Bystřice nad Pernštejnem, gymnázium",
      date: "2013-11-15",
      acoustic: false,
    },
    {
      title: "Vánoční charitativní koncert pro Modrou berušku",
      place: "Brno, Fléda",
      date: "2013-12-8",
      acoustic: false,
      gallery: ["Berunda_1", "Berunda_2", "Berunda_3"],
    },
    {
      title: "Millenium club",
      place: "Bystřice nad Pernštejnem",
      date: "2013-12-18",
      acoustic: false,
    },
    {
      title: "Maturitní ples Gybnp",
      place: "Bystřice nad Pernštejnem",
      date: "2014-8-2",
      acoustic: true,
    },
    {
      title: "Kavárna Franqueza I",
      place: "Bystřice nad Pernštejnem",
      date: "2014-3-21",
      acoustic: true,
      gallery: ["Fran14_1", "Fran14_2", "Fran14_3", "Fran14_4"],
      photographer: "MD",
    },
    {
      title: "Křest CD SměSKA",
      place: "Bystřice nad Pernštejnem",
      date: "2014-4-26",
      acoustic: false,
    },
    {
      title: "Majáles Zubří země",
      place: "Bystřice nad Pernštejnem",
      date: "2014-9-13",
      acoustic: false,
    },
    {
      title: "Summer night vol.I",
      place: "Brno",
      date: "2014-6-14",
      acoustic: false,
    },
    {
      title: "Pelíšek fest",
      place: "Bystřice nad Pernštejnem",
      date: "2014-6-28",
      acoustic: false,
    },
    {
      title: "Slavnosti Pernštejnského panství",
      place: "",
      date: "2014-7-4",
      acoustic: false,
    },
    {
      title: "Rock pro Jirku",
      place: "Dolní Vilémovice",
      date: "2014-7-11",
      acoustic: false,
    },
    {
      title: "Podmitrovská rocková noc",
      place: "Podmitrov",
      date: "2014-7-19",
      acoustic: false,
    },
    {
      title: "Backstage of Stařeč",
      place: "Stařeč",
      date: "2014-7-19",
      acoustic: false,
    },
    {
      title: "Kavárna Franqueza II",
      place: "Bystřice nad Pernštejnem",
      date: "2014-8-15",
      acoustic: true,
    },
    {
      title: "Wůdštok na psím kruháči 1",
      place: "Bystřice nad Pernštejnem",
      date: "2014-8-29",
      acoustic: false,
    },
    {
      title: "Svatba Dufek + Kozáčková",
      place: "Ubušínek",
      date: "2014-9-6",
      acoustic: true,
    },
    {
      title: "Svatba",
      place: "Dalečín",
      date: "2014-9-6",
      acoustic: true,
    },
    {
      title: "Zastávka Dalečín",
      place: "Dalečín",
      date: "2014-9-13",
      acoustic: false,
    },
    {
      title: "Rodinná oslava (Pavlačkovi)",
      place: "Bystřice nad Pernštejnem",
      date: "2014-9-27",
      acoustic: false,
    },
    {
      title: "Křídla",
      place: "Křídla",
      date: "2014-9-27",
      acoustic: false,
    },
    {
      title: "Funny Fest (Nadosah)",
      place: "Bystřice nad Pernštejnem",
      date: "2014-11-28",
      acoustic: false,
    },
    {
      title: "NRGTour",
      place: "Bystřice nad Pernštejnem",
      date: "2014-12-6",
      acoustic: false,
    },
    {
      title: "NRGTour",
      place: "Moravské Budějovice",
      date: "2014-12-20",
      acoustic: false,
    },
    {
      title: "NRGTour",
      place: "Jihlava",
      date: "2014-12-26",
      acoustic: false,
    },
    {
      title: "NRGTour",
      place: "Velké Meziříčí",
      date: "2014-12-27",
      acoustic: false,
    },
    {
      title: "NRGTour",
      place: "Třebíč",
      date: "2015-1-3",
      acoustic: false,
    },
    {
      title: "Vysočina hledá talent",
      place: "Jihlava",
      date: "2015-1-24",
      acoustic: false,
    },
    {
      title: "Kavárna Franqueza III",
      place: "Bystřice nad Pernštejnem",
      date: "2015-2-20",
      acoustic: true,
      gallery: ["Franqueza15_1", "Franqueza15_2", "Franqueza15_3"],
      photographer: "MD",
    },
    {
      title: "Rodinná oslava v (Pečinkovi)",
      place: "Bystřice nad Pernštejnem, Di Pietro",
      date: "2015-5-30",
      acoustic: true,
    },
    {
      title: "Rečická kavárna",
      place: "Žďár nad Sázavou",
      date: "2015-6-27",
      acoustic: true,
    },
    {
      title: "Vírské vanutí",
      place: "Vír",
      date: "2015-8-1",
      acoustic: true,
    },
    {
      title: "Akustický podvečer",
      place: "Bystřice nad Pernštejnem",
      date: "2015-8-15",
      acoustic: true,
    },
    {
      title: "Wůdštok na psím kruháči 2",
      place: "Bystřice nad Pernštejnem",
      date: "2015-8-29",
      acoustic: false,
    },
    {
      title: "Semilaso - ZakázanÝovoce",
      place: "Brno",
      date: "2015-10-22",
      acoustic: false,
    },
    {
      title: "NRGT vol. II",
      place: "Moravské Budějovice",
      date: "2015-12-18",
      acoustic: false,
    },
    {
      title: "NRGT vol. II",
      place: "Havlíčkův Brod",
      date: "2015-12-23",
      acoustic: false,
    },
    {
      title: "NRGT vol. II",
      place: "Bystřice nad Pernštejnem",
      date: "2015-12-26",
      acoustic: false,
    },
    {
      title: "NRGT vol. II",
      place: "Velké Meziříčí",
      date: "2016-1-2",
      acoustic: false,
    },
    {
      title: "NRGT vol. II",
      place: "Jihlava",
      date: "2016-1-8",
      acoustic: false,
    },
    {
      title: "NRGT vol. II",
      place: "Třebíč",
      date: "2016-1-9",
      acoustic: false,
    },
    {
      title: "Pístovské mokřady",
      place: "Pístov",
      date: "2016-3-26",
      acoustic: false,
    },
    {
      title: "Pizzerie di Pietro I + AMaTer",
      place: "Bystřice nad Pernštejnem",
      date: "2016-4-9",
      acoustic: true,
    },
    {
      title: "Zámek Belcredi",
      place: "Brno",
      date: "2016-6-11",
      acoustic: true,
    },
    {
      title: "Pizzerie di Pietro II + AMaTer",
      place: "Bystřice nad Pernštejnem",
      date: "2016-11-12",
      acoustic: true,
    },
    {
      title: "Pelíšek fest",
      place: "Bystřice nad Pernštejnem",
      date: "2016-6-25",
      acoustic: false,
    },
    {
      title: "Slavnosti Pernštejnského panství",
      place: "Nedvědice",
      date: "2016-7-1",
      acoustic: false,
    },
    {
      title: "Wůdštok na psím kruháči 3",
      place: "Bystřice nad Pernštejnem",
      date: "2016-8-27",
      acoustic: false,
    },
    {
      title: "Funny Fest",
      place: "Bystřice nad Pernštejnem",
      date: "2016-10-27",
      acoustic: false,
    },
    {
      title: "Pizzerie di Pietro III",
      place: "Bystřice nad Pernštejnem",
      date: "2016-11-12",
      acoustic: true,
    },
    {
      title: "Maturitní ples GyBnP",
      place: "Bystřice nad Pernštejnem",
      date: "2016-12-11",
      acoustic: false,
    },
    {
      title: "Orlovna",
      place: "Bystřice nad Pernštejnem",
      date: "2017-4-15",
      acoustic: true,
    },
    {
      title: "Batiskaf s AMaTer",
      place: "Žďár nad Sázavou",
      date: "2017-4-22",
      acoustic: true,
    },
    {
      title: "Festival minipivovarů",
      place: "Bystřice nad Pernštejnem, Eden",
      date: "2017-6-3",
      acoustic: true,
    },
    {
      title: "Pivní slavnosti",
      place: "Štěpánov nad Svratkou",
      date: "2017-7-22",
      acoustic: true,
    },
    {
      title: "4FunFest u Píláku",
      place: "Žďár nad Sázavou",
      date: "2017-7-23",
      acoustic: true,
    },
    {
      title: "Kavárna Franqueza IV",
      place: "Bystřice nad Pernštejnem",
      date: "2017-7-25",
      acoustic: true,
    },
    {
      title: "Wůdštok na psím kruháči 4",
      place: "Bystřice nad Pernštejnem",
      date: "2017-8-26",
      acoustic: false,
    },
    {
      title: "TOP 09",
      place: "Jihlava",
      date: "2017-10-1",
      acoustic: false,
    },
    {
      title: "Maturitní ples GyBnP",
      place: "Bystřice nad Pernštejnem",
      date: "2018-1-20",
      acoustic: false,
    },
    {
      title: "Nahrávací studio Orlí",
      place: "Brno",
      date: "2018-3-8",
      acoustic: false,
      gallery: ["Orli_1", "Orli_2", "Orli_3"],
      photographer: "MV",
    },
    {
      title: "Melodka",
      place: "Brno, Melodka",
      date: "2018-4-6",
      acoustic: false,
      gallery: ["Melodka18dub_1", "Melodka18dub_2", "Melodka18dub_3"],
      photographer: "MV",
    },
    {
      title: "Beerpong",
      place: "Brno, Eleven Club",
      date: "2018-4-25",
      acoustic: false,
      gallery: ["Beerpong_1", "Beerpong_2", "Beerpong_3", "Beerpong_4"],
      photographer: "MV",
    },
    {
      title: "Soukromá akce",
      place: "Bruntál",
      date: "2018-6-23",
      acoustic: false,
    },
    {
      title: "Pelíšek fest",
      place: "Bystřice nad Pernštejnem",
      date: "2018-6-30",
      acoustic: false,
    },
    {
      title: "Slavnosti Pernštejnského panství",
      place: "Nedvědice",
      date: "2018-7-4",
      acoustic: false,
    },
    {
      title: "Festival minipivovarů",
      place: "Bystřice nad Pernštejnem, Eden",
      date: "2018-7-21",
      acoustic: false,
    },
    {
      title: "Rock na cihelně",
      place: "Lužice",
      date: "2018-7-28",
      acoustic: false,
    },
    {
      title: "Zubštejn času",
      place: "Pivonice",
      date: "2018-8-10",
      acoustic: false,
    },
    {
      title: "Funny Fest",
      place: "Velké Meziříčí",
      date: "2018-8-10",
      acoustic: false,
    },
    {
      title: "Wůdštok na psím kruháči 5",
      place: "Bystřice nad Pernštejnem",
      date: "2018-8-24",
      acoustic: false,
    },
    {
      title: "Funny Fest",
      place: "Žďár nad Sázavou",
      date: "2018-9-7",
      acoustic: false,
    },
    {
      title: "Junk Head Dirt Contest",
      place: "Kateřinice",
      date: "2018-9-8",
      acoustic: false,
    },
    {
      title: "Boyz are Back in Town",
      place: "Svitavy",
      date: "2018-9-29",
      acoustic: false,
    },
    {
      title: "FAST FEST",
      place: "Brno",
      date: "2018-11-2",
      acoustic: false,
    },
    {
      title: "John Wolfhooker, Prospective",
      place: "Brno, Eleven Club",
      date: "2018-10-20",
      acoustic: false,
    },
    {
      title: "ARC Fest",
      place: "Brno",
      date: "2018-10-23",
      acoustic: false,
      gallery: ["ArcBar_1", "ArcBar_2", "ArcBar_3"],
      photographer: "MV",
    },
    {
      title: "Melodka",
      place: "Brno, Melodka",
      date: "2018-11-2",
      acoustic: false,
      gallery: [
        "Melodka18_1",
        "Melodka18_2",
        "Melodka18_3",
        "Melodka18_4",
        "Melodka18_5",
        "Melodka18_6",
      ],
      photographer: "MV",
    },
    {
      title: "Maturitní ples GyBnP",
      place: "Bystřice nad Pernštejnem",
      date: "2019-1-19",
      acoustic: false,
    },
    {
      title: "Starobrno contest Majáles",
      place: "Brno, Eleven Club",
      date: "2019-4-17",
      acoustic: false,
      gallery: ["Starobrno_1", "Starobrno_2", "Starobrno_3", "Starobrno_4"],
    },
    {
      title: "Majáles VFU",
      place: "Brno",
      date: "2019-4-30",
      acoustic: false,
    },
    {
      title: "Wůdštok na psím kruháči 6",
      place: "Bystřice nad Pernětejnem",
      date: "2019-8-17",
      acoustic: false,
    },
    {
      title: "Bandzone showcase",
      place: "Praha",
      date: "2020-1-20",
      acoustic: false,
    },
    {
      title: "U bílé kočky a černého psa",
      place: "Žďár nad Sázavou",
      date: "2020-2-21",
      acoustic: true,
    },
    {
      title: "Music Bar",
      place: "Vyškov",
      date: "2020-3-6",
      acoustic: true,
    },
    {
      title: "Kočov",
      place: "Kočov",
      date: "2020-6-27",
      acoustic: false,
    },
    {
      title: "Wůdštok na psím kruháči 7",
      place: "Bystřice nad Pernštejnem",
      date: "2020-9-28",
      acoustic: false,
    },
    {
      title: "Music Bar II",
      place: "Vyškov",
      date: "2020-9-4",
      acoustic: true,
    },
    {
      title: "Hanácké náměstí",
      place: "Kroměříž",
      date: "2020-9-16",
      acoustic: true,
    },
    {
      title: "Klofáč narozky",
      place: "Nebovidy",
      date: "2021-6-19",
      acoustic: true,
    },
    {
      title: "JAMU Music Lab",
      place: "Brno",
      date: "2021-7-14",
      acoustic: true,
      gallery: ["JAMU1_1", "JAMU1_2", "JAMU1_3"],
      photographer: "KG",
    },
    {
      title: "Svatba Hanka a Kuba",
      place: "Komořany",
      date: "2021-8-7",
      acoustic: true,
    },
    {
      title: "Slučák",
      place: "Podmitrov",
      date: "2021-9-8",
      acoustic: true,
    },
    {
      title: "Majáles",
      place: "Moravský Krumlov",
      date: "2022-5-6",
      acoustic: false,
      gallery: ["MorKrum_1", "MorKrum_2", "MorKrum_3"],
    },
    {
      title: "Melodka",
      place: "Brno, Melodka",
      date: "2022-5-11",
      acoustic: false,
      gallery: [
        "Melodka22_2",
        "Melodka22_3",
        "Melodka22_4",
        "Melodka22_5",
        "Melodka22_6",
        "Melodka22_7",
        "Melodka22_8",
        "Melodka22_9",
      ],
      photographer: "KG",
    },
    {
      title: "Roudnice",
      place: "Roudnice nad Labem",
      date: "2022-7-30",
      acoustic: false,
    },
    {
      title: "JAMU Music Lab",
      place: "Brno",
      date: "2022-8-10",
      acoustic: true,
      gallery: ["JAMU2_1", "JAMU2_2", "JAMU2_3"],
      photographer: "KG",
    },
    {
      title: "Wůdštok na psím kruháči 8",
      place: "Bystřice nad Pernštejnem",
      date: "2022-8-20",
      acoustic: false,
      gallery: ["Wudstok8_3", "Wudstok8_4", "Wudstok8_5"],
      photographer: "KG",
    },
    {
      title: "Vánoční trhy",
      place: "Karviná",
      date: "2022-12-16",
      acoustic: false,
      gallery: ["Karvina_1", "Karvina_2"],
      photographer: "KG",
    },
    {
      title: "Melodka",
      place: "Brno, Melodka",
      date: "2023-4-19",
      acoustic: false,
      gallery: ["Melodka23dub_1", "Melodka23dub_2"],
      photographer: "KG",
    },
    {
      title: "Festival mladých kapel",
      place: "Brno, Vinohrady",
      date: "2023-6-14",
      acoustic: false,
    },
    {
      title: "Teplice",
      place: "Teplice",
      date: "2023-7-8",
      acoustic: false,
    },
    {
      title: "Pivovar Starobrno",
      place: "Brno",
      date: "2023-7-15",
      acoustic: false,
    },
    {
      title: "Wůdštok na psím kruháči 9",
      place: "Bystřice nad Pernštejnem",
      date: "2023-8-19",
      acoustic: false,
    },
    {
      title: "Bavíme se na Vinohradech",
      place: "Brno, Vinohrady",
      date: "2023-9-2",
      acoustic: false,
    },
    {
      title: "Hudba z FEKTu",
      place: "Brno, FEKT",
      date: "2023-9-20",
      acoustic: false,
    },
    {
      title: "Svatováclavské pivní slavnosti",
      place: "Ostrava, Zámek Zábřeh",
      date: "2023-9-28",
      acoustic: false,
      gallery: [
        "Ostrava_1",
        "Ostrava_2",
        "Ostrava_3",
        "Ostrava_4",
        "Ostrava_5",
      ],
      photographer: "KG",
    },
    {
      title: "Melodka Farewell",
      place: "Brno, Melodka",
      date: "2023-12-21",
      acoustic: false,
      gallery: [
        "Melodka_Farewell_1",
        "Melodka_Farewell_2",
        "Melodka_Farewell_3",
        "Melodka_Farewell_4",
        "Melodka_Farewell_5",
        "Melodka_Farewell_6",
      ],
      photographer: "KG",
    },
    {
      title: "East Clintwood, Vědomí",
      place: "Praha, Strahov 007",
      date: "2024-4-25",
      acoustic: false,
    },
    {
      title: "Nová Melodka",
      place: "Brno, Melodka",
      date: "2024-4-15",
      acoustic: false,
    },
    {
      title: "Megakoncert kapely Highland",
      place: "Valtice, náměstí",
      date: "2024-7-13",
      acoustic: false,
      gallery: ["Valtice_1", "Valtice_2", "Valtice_3", "Valtice_4"],
      photographer: "LZ",
    },
    {
      title: "Poslech Music Bar",
      place: "Brno, Česká",
      date: "2024-8-21",
      acoustic: true,
    },
    {
      title: "Kaplické městské slavnosti",
      place: "Kaplice",
      date: "2024-8-24",
      gallery: ["Kaplice_1", "Kaplice_2", "Kaplice_3", "Kaplice_4"],
      photographer: "KK",
      acoustic: false,
    },
    {
      title: "Koncert pro Park",
      place: "Praha 13",
      date: "2024-9-1",
      acoustic: false,
    },
    {
      title: "Tradiční Býtešské hody",
      place: "Velká Býteš",
      date: "2024-9-7",
      gallery: ["VB_1", "VB_2", "VB_3", "VB_4"],
      photographer: "LZ",
      acoustic: false,
    },
    {
      title: "Vinobraní v Château Valtice",
      place: "Valtice",
      date: "2024-9-21",
      acoustic: false,
    },
    {
      title: "Strahov OpenAir",
      place: "Praha, Strahov",
      date: "2024-9-25",
      gallery: ["Strahov_1"],
      photographer: "KG",
      acoustic: false,
    },
    {
      title: "Civilní obrana",
      place: "Brno, Fléda",
      date: "2025-2-15",
      gallery: [
        "Fleda_1",
        "Fleda_2",
        "Fleda_3",
        "Fleda_4",
        "Fleda_5",
        "Fleda_6",
      ],
      photographer: "KG",
      acoustic: false,
    },
    {
      title: "Devil hates Sekáč",
      place: "Kopřivnice",
      date: "2025-2-22",
      acoustic: false,
    },
    {
      title: "Finále SAI",
      place: "Praha, Storm",
      date: "2025-4-15",
      acoustic: false,
    },
    {
      title: "Třídní sraz",
      place: "Rozsice",
      date: "2025-5-23",
      acousstic: true,
    },
    {
      title: "Rybičky 48 FEST",
      place: "Kutná Hora",
      date: "2025-5-24",
      gallery: ["KutnaHora_1", "KutnaHora_2", "KutnaHora_3", "KutnaHora_4"],
      photographer: "KG",
      acoustic: false,
    },
    {
      title: "Písek",
      place: "Písek",
      date: "2025-6-13",
      acoustic: false,
    },
    {
      title: "Okolo Třeboně",
      place: "Třeboň",
      date: "2025-7-6",
      acoustic: false,
    },
    {
      title: "Vysočina Fest",
      place: "Jihlava",
      date: "2025-7-6",
      acoustic: false,
    },
  ],
};
